env:
  POSTGRES_PASSWORD: insecure
  POSTGRES_DB: nextcloud
  POSTGRES_USER: nextcloud
  POSTGRES_HOST: nextcloud-db
  PGID: "1040"
  PUID: "1040"

nextcloud_root: /media/data/cloud

nextcloud_keeweb_version: 0.5.1
nextcloud_keeweb_dir: "{{ nextcloud_root }}/config/www/nextcloud/apps"
