---

- name: install zigbee2mqtt in docker
  docker_container:
    name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    network_mode: host
    restart_policy: always
    volumes:
    - "/opt/zigbee2mqtt:/app/data"
    - "/run/udev:/run/udev:ro"
    env:
      TZ: "Europe/Moscow"
    devices:
    - "/dev/ttyACM0:/dev/ttyACM0"
    privileged: yes
  tags:
  - zigbee2mqtt

- name: copy config to destination directory
  template:
    src: templates/configuration.yaml.j2
    dest: /opt/zigbee2mqtt/configuration.yaml
    notify: restart zigbee2mqtt
  tags:
  - zigbee2mqtt
