---
- name: add docker apt-key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker deb repository
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/debian stretch stable
    state: present

- name: install docker packages
  apt:
    package:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python-setuptools
    - python-pip
    state: latest
    update_cache: yes

- name: install docker-py
  pip:
    name: docker
    version: 2.7.0
