---

- name: Install plex arm container
  docker_container:
    name: plex
    image: lsioarmhf/plex
    restart_policy: always
    env: "{{ env }}"
    network_mode: host
    volumes:
    - "{{ mounts.torrent.movies }}:/data/torrent/movies"
    - "{{ mounts.torrent.tvshows }}:/data/torrent/tvshows"
    - "{{ mounts.movies }}:/data/movies"
    - "{{ mounts.config }}:/config"
  tags: 
    - plex

