- name: add syncthing apt-key
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: add syncthing deb repository
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present

- name: install syncthing package
  apt:
    package:
    - syncthing
    state: latest
    update_cache: yes
  tags:
    - syncthing

- name: create syncthing user
  user:
    name: syncthing
    uid: 1040
    groups: storage,www-data
  tags:
    - syncthing

- name: run syncthing unit
  systemd:
    name: syncthing@syncthing
    state: started
    enabled: yes
  tags:
    - syncthing
